spring:
  application:
    name: Brunner-Wydra-SwenProjekt

  datasource:
    url: jdbc:postgresql://localhost:5432/swenprojekt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
